# Project 2: Python-Based Data Processing

## Summer Training - LinuxWorld Informatics Pvt. Ltd.

**Name:** Payal Sharma

### Objective
To understand how Python and Pandas can be used to process and analyze tabular data.

## Importing Required Library

Pandas is one of the most popular Python libraries used for data processing and analysis.

In [1]:
import pandas as pd

## Loading the Dataset

In [2]:
df = pd.read_csv("student_data.csv")

df

   Student_ID   Name  Age Course  Marks
0         101  Payal   20    CSE     85
1         102   Aman   21    CSE     90
2         103   Riya   20     IT     78
3         104  Rahul   22    CSE     88
4         105  Sneha   21    ECE     95
5         106  Karan   23     IT     76
6         107  Priya   20    CSE     82
7         108   Neha   22    ECE     91
8         109  Rohit   21     IT     80
9         110  Ankit   20    CSE     87

## Display First Five Records

In [3]:
df.head()

   Student_ID   Name  Age Course  Marks
0         101  Payal   20    CSE     85
1         102   Aman   21    CSE     90
2         103   Riya   20     IT     78
3         104  Rahul   22    CSE     88
4         105  Sneha   21    ECE     95

## Dataset Information

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Course      10 non-null     str
 4   Marks       10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

## Statistical Summary

In [5]:
df.describe()

       Student_ID        Age      Marks
count    10.00000  10.000000  10.000000
mean    105.50000  21.000000  85.200000
std       3.02765   1.054093   6.124632
min     101.00000  20.000000  76.000000
25%     103.25000  20.000000  80.500000
50%     105.50000  21.000000  86.000000
75%     107.75000  21.750000  89.500000
max     110.00000  23.000000  95.000000

## Processing the Data

In [6]:
print("Average Marks:", df["Marks"].mean())
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Average Marks: 85.2
Highest Marks: 95
Lowest Marks: 76

## Students Scoring More Than 85 Marks

In [7]:
df[df["Marks"] > 85]

   Student_ID   Name  Age Course  Marks
1         102   Aman   21    CSE     90
3         104  Rahul   22    CSE     88
4         105  Sneha   21    ECE     95
7         108   Neha   22    ECE     91
9         110  Ankit   20    CSE     87

## Conclusion

This project demonstrates how Python and Pandas can be used to load, inspect, process, and analyze structured data. It forms the foundation for future Data Science and Machine Learning projects.