# Project 3: Data Cleaning and Preparation

## Summer Training – LinuxWorld Informatics Pvt. Ltd.

**Name:** Payal Sharma

### Objective
Prepare raw data for analysis by identifying and handling missing values, duplicate records, and inconsistencies to create a clean dataset.

## Importing Required Libraries

In [1]:
import pandas as pd

## Loading the Dataset

In [2]:
df = pd.read_csv("student_data.csv")
df

    Student_ID   Name   Age Course  Marks
0          101  Payal  20.0    CSE   85.0
1          102   Aman  21.0    CSE   90.0
2          103   Riya   NaN     IT   78.0
3          104  Rahul  22.0    CSE   88.0
4          104  Rahul  22.0    CSE   88.0
5          105    NaN  21.0    ECE   95.0
6          106  Karan  23.0     IT    NaN
7          107  Priya  20.0    CSE   82.0
8          108   Neha  22.0    ECE   91.0
9          109  Rohit  21.0     IT   80.0
10         110  Ankit  20.0    CSE   87.0

## Inspect Dataset Structure

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  11 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     float64
 3   Course      11 non-null     str
 4   Marks       10 non-null     float64
dtypes: float64(2), int64(1), str(2)
memory usage: 572.0 bytes

## Checking Missing Values

In [4]:
df.isnull().sum()

Student_ID    0
Name          1
Age           1
Course        0
Marks         1
dtype: int64

## Removing Duplicate Records

In [5]:
df = df.drop_duplicates()
df

    Student_ID   Name   Age Course  Marks
0          101  Payal  20.0    CSE   85.0
1          102   Aman  21.0    CSE   90.0
2          103   Riya   NaN     IT   78.0
3          104  Rahul  22.0    CSE   88.0
5          105    NaN  21.0    ECE   95.0
6          106  Karan  23.0     IT    NaN
7          107  Priya  20.0    CSE   82.0
8          108   Neha  22.0    ECE   91.0
9          109  Rohit  21.0     IT   80.0
10         110  Ankit  20.0    CSE   87.0

## Handling Missing Values

In [6]:
df["Name"] = df["Name"].fillna("Unknown")

df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

## Clean Dataset

In [7]:
df

    Student_ID     Name        Age Course      Marks
0          101    Payal  20.000000    CSE  85.000000
1          102     Aman  21.000000    CSE  90.000000
2          103     Riya  21.111111     IT  78.000000
3          104    Rahul  22.000000    CSE  88.000000
5          105  Unknown  21.000000    ECE  95.000000
6          106    Karan  23.000000     IT  86.222222
7          107    Priya  20.000000    CSE  82.000000
8          108     Neha  22.000000    ECE  91.000000
9          109    Rohit  21.000000     IT  80.000000
10         110    Ankit  20.000000    CSE  87.000000

## Verifying Clean Data

In [8]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Course        0
Marks         0
dtype: int64

## Conclusion

The raw dataset was successfully cleaned by:

- Removing duplicate records
- Handling missing values
- Inspecting dataset structure
- Preparing a clean, analysis-ready dataset

This cleaned dataset can now be used for data analysis and Machine Learning.